core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('profiles/', include('profiles.urls')),
]

index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
    path('today/', views.today, name='today'),
    path('project/<int:id>/', views.project, name='project'),
    
    
    # Functions
    path('post/create_new_project/', views.create_new_project, name='create_new_project'),
    
    path('post/edit_project_name/<int:id>/', views.edit_project_name, name='edit_project_name'),
    path('post/add_allowed_user/<int:id>/', views.add_allowed_user, name='add_allowed_user'),
    path('post/remove_allowed_user/<int:id>/', views.remove_allowed_user, name='remove_allowed_user'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_out/', views.sign_out, name='sign_out'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} {% endblock %} </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    

    <style>


        body{
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
            background-color: #faf9f8;

        }

        .content {
            display: grid;

            grid-template-columns: 280px 1fr;

            height: 94.5svh;
        }

    </style>

    {% block style %}
    {% endblock %}

</head>
<body>
    
    {% include 'navbar.html' %}

    <div class="content">
        {% include 'sidebar.html' %}

        {% block content %}
        {% endblock %}
    </div>

    {% block script %}
    {% endblock %}

</body>
</html>

templates/navbar.html
{% block style %}

<style>
    .m_navbar {
        background-image: linear-gradient(to bottom, #2564cf, #1f56b4);
        padding: 5px 50px;

        display: flex;
        justify-content: space-between;
        align-items: center;

        font-size: 18px;
        height: 4svh;

    }

    .title{
        margin-bottom: 0 !important;
    }

    .m_icon {
        color: white;
        padding: 10px 25px;

        border-radius: 5px;

        transition: all ease .3s;
    }

    .m_icon:hover {
        background-color: rgba(0, 0, 0, .1);
    }

    .logo {
        padding: 15px 0;
        color: white;
        font-size: 16px;
        font-weight: bold;
    }

    .logo:hover{
        cursor: pointer;
    }

    .menu{
        display: flex;
        align-items: center;
    }


</style>

{% endblock %}


<div class="m_navbar">
    <span class="logo">Live To Do</span>
    <div class="menu">
        <a href="#"><i class="m_icon fa-solid fa-wrench"></i></a>
        <a href="#"><i class="m_icon fa-solid fa-question"></i></a>
        
        {% if request.user.is_authenticated %}
        <a href="#"><i class="m_icon fa-solid fa-user"></i></a>
        <a href="{% url 'profiles:sign_out' %}"><i class="m_icon fa-solid fa-arrow-right-from-bracket"></i></a>
        {% else %}
        <a href="{% url 'profiles:sign_in' %}"><i class="m_icon fa-solid fa-sign-in"></i></a>
        {% endif %}
    </div>
</div>

templates/sidebar.html
{% load static %}
{% block style %}

<link rel="stylesheet" href="{% static 'profiles/sidebar.css' %}">

{% endblock %}


<div class="m_sidebar">
    {% if not request.user.is_authenticated %}
    <ul>
        <a href="{% url 'profiles:sign_in' %}"><li class="list-item" id="SignInBtn"><i class="list_icon fa-solid fa-sign-in"></i> Sign In</li></a>
        <a href="{% url 'profiles:sign_up' %}"><li class="list-item" id="SignUpBtn"><i class="list_icon fa-solid fa-sign-up"></i></i> Sign Up</li></a>
    </ul>
    <hr width="85%" color="#e1dfdd">
    {% endif %}
    <ul>
        <a href="{% url 'index:today' %}"><li class="list-item" id="todayBtn"><i class="list_icon fa-regular fa-sun"></i> Today</li></a>
        <a href="#"><li class="list-item"><i class="list_icon fa-regular fa-star"></i> Important</li></a>
        <a href="#"><li class="list-item"><i class="list_icon fa-regular fa-calendar"></i> Plans</li></a>
    </ul>
    <hr width="85%" color="#e1dfdd">
    <ul>

        {% for i in request.user.profile.projects.all %}
            <a href="{% url 'index:project' i.id %}"><li class="list-item"><i class="list_icon fa-regular fa-circle"></i> {{ i.title }} {{ i.id }} </li></a>
        {% endfor %}
        <a href="{% url 'index:create_new_project' %}"><li style="color: #2564cf;" class="list-item"><i class="list_icon fa-regular fa-plus"></i> New Project</li></a>
    </ul>
    <hr width="85%" color="#e1dfdd">
    <ul>
        {% for i in request.user.profile.projects_allowed_in.all %}
            <a href="{% url 'index:project' i.id %}"><li class="list-item"><i class="list_icon fa-regular fa-circle"></i> {{ i.title }} {{ i.id }} </li></a>
        {% endfor %}

    </ul>

</div>

<script>
    // Change the hard-coded part later!
    if(window.location.pathname === '{% url "index:today" %}'){
        document.getElementById('todayBtn').style.backgroundColor = '#eff6fc';
        document.getElementById('todayBtn').style.borderLeft = '2px solid #2564cf';
        document.getElementById('todayBtn').style.color = '#292827';
    } else if (window.location.pathname === ''){
        document.getElementById('important-btn').style.backgroundColor = '#eff6fc';
        document.getElementById('today-btn').style.color = '#292827';
    } else if (window.location.pathname === ''){
        document.getElementById('plans-btn').style.backgroundColor = '#eff6fc';
        document.getElementById('today-btn').style.color = '#292827';
    } else if (window.location.pathname === '{% url "profiles:sign_in" %}'){
        document.getElementById('SignInBtn').style.backgroundColor = '#eff6fc';
        document.getElementById('SignInBtn').style.color = '#292827';
    } else if (window.location.pathname === '{% url "profiles:sign_up" %}'){
        document.getElementById('SignUpBtn').style.backgroundColor = '#eff6fc';
        document.getElementById('SignUpBtn').style.color = '#292827';
    }


</script>